In [102]:
import pandas as pd

In [103]:
df = pd.read_csv(r'loan_approval.csv')
df.head()

,name,city,income,credit_score,loan_amount,years_employed,points,loan_approved
0,Allison Hill,East Jill,113810,389,39698,27,50.0,False
1,Brandon Hall,New Jamesside,44592,729,15446,28,55.0,False
2,Rhonda Smith,Lake Roberto,33278,584,11189,13,45.0,False
3,Gabrielle Davis,West Melanieview,127196,344,48823,29,50.0,False
4,Valerie Gray,Mariastad,66048,496,47174,4,25.0,False

In [104]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2000 entries, 0 to 1999
Data columns (total 8 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   name            2000 non-null   object
 1   city            2000 non-null   object
 2   income          2000 non-null   int64
 3   credit_score    2000 non-null   int64
 4   loan_amount     2000 non-null   int64
 5   years_employed  2000 non-null   int64
 6   points          2000 non-null   float64
 7   loan_approved   2000 non-null   bool
dtypes: bool(1), float64(1), int64(4), object(2)
memory usage: 111.5+ KB

In [105]:
df.isnull().sum()

name              0
city              0
income            0
credit_score      0
loan_amount       0
years_employed    0
points            0
loan_approved     0
dtype: int64

In [106]:
df.drop(columns = ['name', 'city', 'points'], axis = 1, inplace = True)

In [107]:
df.head()

   income  credit_score  loan_amount  years_employed  loan_approved
0  113810           389        39698              27          False
1   44592           729        15446              28          False
2   33278           584        11189              13          False
3  127196           344        48823              29          False
4   66048           496        47174               4          False

In [108]:
df['loan_approved'].value_counts()

loan_approved
False    1121
True      879
Name: count, dtype: int64

In [109]:
from sklearn.preprocessing import LabelEncoder

In [110]:
le = LabelEncoder()

In [111]:
df['loan_approved'] = le.fit_transform(df['loan_approved'])

In [112]:
df.head()

   income  credit_score  loan_amount  years_employed  loan_approved
0  113810           389        39698              27              0
1   44592           729        15446              28              0
2   33278           584        11189              13              0
3  127196           344        48823              29              0
4   66048           496        47174               4              0

In [113]:
x = df.drop(columns = ['loan_approved'])
y = df['loan_approved']

In [114]:
from sklearn.model_selection import train_test_split

In [115]:
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size = 0.2, random_state = 42)

In [116]:
x_train.shape, x_test.shape, y_train.shape, y_test.shape

((1600, 4), (400, 4), (1600,), (400,))

In [117]:
from sklearn.preprocessing import StandardScaler

In [118]:
scaling = StandardScaler()

In [119]:
x_train = scaling.fit_transform(x_train)
x_test = scaling.transform(x_test)

In [120]:
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.ensemble import AdaBoostClassifier
from sklearn.ensemble import GradientBoostingClassifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn.svm import SVC
from xgboost import XGBClassifier

In [121]:
from sklearn.metrics import classification_report, accuracy_score, precision_score, recall_score, f1_score, confusion_matrix

In [122]:
models = {
    'Logistic Regression' : LogisticRegression(),
    'Decision Tree' : DecisionTreeClassifier(),
    'Random Forest' : RandomForestClassifier(n_estimators = 100),
    'AdaBoost' : AdaBoostClassifier(n_estimators = 100),
    'GradientBoosting' : GradientBoostingClassifier(),
    'KNeighbors' : KNeighborsClassifier(n_neighbors = 5),
    'SVC' : SVC(),
    'XGBoost' : XGBClassifier(n_estimators = 10)
}

In [123]:
results = []

for name, model in models.items():
    model.fit(x_train, y_train)

    y_pred = model.predict(x_test)

    accuracy = accuracy_score(y_test, y_pred)
    precision = precision_score(y_test, y_pred)
    recall = recall_score(y_test, y_pred)
    f1 = f1_score(y_test, y_pred)

    results.append({
        'Model Name' : name,
        'Accuracy' : accuracy,
        'Precision' : precision,
        'Recall' : recall,
        'F1 Score' : f1
    })

    print('-' * 45)
    print('Model', name)
    print(confusion_matrix(y_test, y_pred))
    print(classification_report(y_test, y_pred))
    print('Accuracy Score', accuracy)

summary_df = pd.DataFrame(results).sort_values(by = 'Accuracy', ascending = False)
summary_df.index = range(1, len(summary_df) + 1)

print('=' * 45)
print('Model Comparsion Summary')
print('=' * 45)
summary_df

---------------------------------------------
Model Logistic Regression
[[195  22]
 [ 24 159]]
              precision    recall  f1-score   support

           0       0.89      0.90      0.89       217
           1       0.88      0.87      0.87       183

    accuracy                           0.89       400
   macro avg       0.88      0.88      0.88       400
weighted avg       0.88      0.89      0.88       400

Accuracy Score 0.885
---------------------------------------------
Model Decision Tree
[[210   7]
 [  7 176]]
              precision    recall  f1-score   support

           0       0.97      0.97      0.97       217
           1       0.96      0.96      0.96       183

    accuracy                           0.96       400
   macro avg       0.96      0.96      0.96       400
weighted avg       0.96      0.96      0.96       400

Accuracy Score 0.965
---------------------------------------------
Model Random Forest
[[210   7]
 [  5 178]]
              precision    recall  f1-score   support

           0       0.98      0.97      0.97       217
           1       0.96      0.97      0.97       183

    accuracy                           0.97       400
   macro avg       0.97      0.97      0.97       400
weighted avg       0.97      0.97      0.97       400

Accuracy Score 0.97
---------------------------------------------
Model AdaBoost
[[211   6]
 [  5 178]]
              precision    recall  f1-score   support

           0       0.98      0.97      0.97       217
           1       0.97      0.97      0.97       183

    accuracy                           0.97       400
   macro avg       0.97      0.97      0.97       400
weighted avg       0.97      0.97      0.97       400

Accuracy Score 0.9725
---------------------------------------------
Model GradientBoosting
[[210   7]
 [  3 180]]
              precision    recall  f1-score   support

           0       0.99      0.97      0.98       217
           1       0.96      0.98      0.97       183

    accuracy                           0.97       400
   macro avg       0.97      0.98      0.97       400
weighted avg       0.98      0.97      0.98       400

Accuracy Score 0.975
---------------------------------------------
Model KNeighbors
[[205  12]
 [ 13 170]]
              precision    recall  f1-score   support

           0       0.94      0.94      0.94       217
           1       0.93      0.93      0.93       183

    accuracy                           0.94       400
   macro avg       0.94      0.94      0.94       400
weighted avg       0.94      0.94      0.94       400

Accuracy Score 0.9375
---------------------------------------------
Model SVC
[[204  13]
 [ 11 172]]
              precision    recall  f1-score   support

           0       0.95      0.94      0.94       217
           1       0.93      0.94      0.93       183

    accuracy                           0.94       400
   macro avg       0.94      0.94      0.94       400
weighted avg       0.94      0.94      0.94       400

Accuracy Score 0.94
---------------------------------------------
Model XGBoost
[[212   5]
 [  5 178]]
              precision    recall  f1-score   support

           0       0.98      0.98      0.98       217
           1       0.97      0.97      0.97       183

    accuracy                           0.97       400
   macro avg       0.97      0.97      0.97       400
weighted avg       0.97      0.97      0.97       400

Accuracy Score 0.975
=============================================
Model Comparsion Summary
=============================================

            Model Name  Accuracy  Precision    Recall  F1 Score
1     GradientBoosting    0.9750   0.962567  0.983607  0.972973
2              XGBoost    0.9750   0.972678  0.972678  0.972678
3             AdaBoost    0.9725   0.967391  0.972678  0.970027
4        Random Forest    0.9700   0.962162  0.972678  0.967391
5        Decision Tree    0.9650   0.961749  0.961749  0.961749
6                  SVC    0.9400   0.929730  0.939891  0.934783
7           KNeighbors    0.9375   0.934066  0.928962  0.931507
8  Logistic Regression    0.8850   0.878453  0.868852  0.873626

In [127]:
gb = GradientBoostingClassifier()
gb.fit(x_train, y_train)

GradientBoostingClassifier()

In [128]:
import pickle

In [129]:
with open('loan_approval.pkl', 'wb') as file:
    pickle.dump(gb, file)